### ISSUE TITLE
Linting returns errors but step still marked as complete successfully.

### ISSUE THREAD

**Issue by DirtDiglett** [samuelmeuli/lint-action#31]
Hi, I'm trying to use a workflow with a lint job and a build job. The build job is set to need the lint to complete successfully to begin so that I don't waste time building if linting returned issues. When linting though, that step is marked successfully completed even if the linters found issues. Is this expected behaviour? Shouldn't the step be marked fail if the linter returns issues?

![firefox_8CXddMBi8n](https://user-images.githubusercontent.com/3527401/77587680-1cc6e200-6f34-11ea-8a11-41822ba1f847.png)

```
name: STAGING - Lint and Build

on:
  push:
    branches-ignore:
      - master
jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: "Install Node Packages"
        run: npm ci

      - name: "Lint - Sass & Javascript"
        uses: samuelmeuli/lint-action@v1.3.0
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true
          stylelint: true

  Build:
    runs-on: ubuntu-latest
    needs: Lint # Only run the build if linting suceeded.

    steps:
      - name: Test
        run: ls -la
```
