### ISSUE TITLE
ESLint always returning parsing error

### ISSUE THREAD

**Issue by sergeh** [samuelmeuli/lint-action#32]
When trying to run ESLint I always end up with this error

> Verifying setup for ESLint…
Verified ESLint setup
Will use ESLint to check the files with extensions js
Linting files in /home/runner/work/aftershokz/aftershokz/scripts/ with ESLint…
Error: Error parsing ESLint JSON output: Unexpected end of JSON input.

Running ESLint locally with the cli works so I'm not sure what's causing this error.

Here's my yml file

```yml
name: Lint

on: pull_request

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Node.js dependencies
        run: npm install

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true
          eslint_dir: scripts/
          stylelint: true
          stylelint_dir: styles/
```
