### ISSUE TITLE
Fails with "unhandled promise rejection" when using SwiftLint

### ISSUE THREAD

**Issue by Jeehut** [samuelmeuli/lint-action#45]
I just tried to use this action for SwiftLint, but I'm getting this error:

```bash
null
/home/runner/work/_actions/samuelmeuli/lint-action/v1.5.0/src/index.js:13
	throw new Error(`Exiting because of unhandled promise rejection`);
	^

Error: Exiting because of unhandled promise rejection
    at process.<anonymous> (/home/runner/work/_actions/samuelmeuli/lint-action/v1.5.0/src/index.js:13:8)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

Here's my job configuration:

```yaml
  swiftlint:
    runs-on: ubuntu-latest
    steps:
    - name: Lint Action
      uses: samuelmeuli/lint-action@v1.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        swiftlint: true
```
