### ISSUE TITLE
Warning: "Unexpected input 'github_token'"

### ISSUE THREAD

**Issue by k001** [samuelmeuli/lint-action#53]
I'm using following the [README.md](https://github.com/samuelmeuli/lint-action/blob/master/README.md#javascript-example-eslint-and-prettier) example for `javascript-example-eslint-and-prettier`, but the workflow shows unexpected input, checking the [inputs](https://github.com/samuelmeuli/lint-action/blob/master/action.yml#L5) that's correct that input is not expected. Also it's trying to push changes to `.github` folder but not sure why. It's a private repo

Here is the error:
```bash
! [remote rejected] master -> master (refusing to allow a GitHub App to create or update workflow `.github/workflows/Lint.yml` without `workflows` permission)
```

This is my `lint.yml` file:
```yaml
name: Lint
on: [push, pull_request]
jobs:
  node-lint-tests:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        os: [ 'ubuntu-latest']
        node: [10, 12]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: install node_modules
        run: yarn install --frozen-lockfile

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true
          prettier: true
          auto_fix: true
```
