### ISSUE TITLE
Black formatter requests changes even if there are no issues

### ISSUE THREAD

**Issue by phrdang** [samuelmeuli/lint-action#84]
Hello, thank you for making this GitHub action, it's been very useful!

I have the following workflow file:

```yml
name: Python (Lint Action)

on: pull_request

jobs:
  format-lint-python:
    name: Format Python with black
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install Python dependencies
        run: pip install black

      - name: Run black
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          black: true
          black_args: --line-length 79  # same max line length as flake8
          auto_fix: true  # auto commit style fixes
```

Oddly, the action requests changes even though there are no linting issues:

<img width="956" alt="Screen Shot 2020-08-04 at 1 32 27 PM" src="https://user-images.githubusercontent.com/35876322/89341961-f1c56b00-d656-11ea-810f-4cb7fee08da5.png">

Any help or a fix of this bug would be appreciated!
